import localFont from 'next/font/local';
import './globals.css';
import { Suspense } from 'react';
import Loading from './loading';

import { UserProvider } from '@auth0/nextjs-auth0/client';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <UserProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <div className='main_container'>
            <Header />
            <Suspense fallback={<Loading />}>{children}</Suspense>
            <Footer />
          </div>
        </body>
      </UserProvider>
    </html>
  );
}
