import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';

import '../globals.css';

import { UserProvider } from '@auth0/nextjs-auth0/client';
import Header from '../../components/Header/Header';
import Footer from '../../components/Footer/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params: { locale } }) {
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <UserProvider>
            <main className='main_container'>
              <Header locale={locale} />
              {children}
              <Footer />
            </main>
          </UserProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
